version: '2.14.1'

services:
#==================================NGINX
        nginx:
                build: requirements/nginx

                container_name: nginx

                ports:
                        - "443:443"

                volumes:
                        - wp_data:/var/www/inception/html
                networks:
                        - inception

                depends_on:
                        - wordpress

                restart: unless-stopped

#==================================MARIADB
        mariadb:
                build: requirements/mariadb

                container_name: mariadb

                ports:
                        - "3306"

                volumes:
                        - db_data:/var/lib/mysql

                networks:
                        - inception

                restart: unless-stopped
#==================================WORDPRESS
        wordpress:
                build: requirements/wordpress

                container_name: wordpress

                ports:
                        - "9000"

                volumes:
                        - wp_data:/var/www/inception/html

                networks:
                        - inception

                depends_on:
                        - mariadb

                restart: unless-stopped
#==================================VOLUMES
volumes:
        db_data:
                driver: local
                driver_opts:
                        type: none
                        device: /home/mlaouedj/Workspace/volumes/mariadb
                        o: bind
        wp_data:
                driver: local
                driver_opts:
                        type: none
                        device: /home/mlaouedj/Workspace/volumes/nginx/html
                        o: bind
#==================================NETWORK
networks:
        inception:
                name: inception
                driver: bridge
